# Generated by Django 5.2.4 on 2025-08-02 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workoutActivityType', models.CharField(max_length=70)),
                ('duration', models.FloatField()),
                ('durationUnit', models.CharField(max_length=10)),
                ('sourceName', models.CharField(max_length=50)),
                ('device', models.CharField(max_length=100)),
                ('creationDate', models.DateTimeField()),
                ('yearCreation', models.IntegerField(blank=True, null=True)),
                ('monthCreation', models.IntegerField(blank=True, null=True)),
                ('dayCreation', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('durationUnit', models.CharField(blank=True, max_length=100, null=True)),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceName', models.CharField(max_length=100)),
                ('sourceVersion', models.CharField(max_length=100)),
                ('creationDate', models.CharField(max_length=100)),
                ('startDate', models.CharField(max_length=100)),
                ('endDate', models.CharField(max_length=100)),
                ('file_reference', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.filereference')),
                ('workout', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('startDate', models.CharField(max_length=100)),
                ('endDate', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('sum', models.CharField(blank=True, max_length=100, null=True)),
                ('average', models.CharField(blank=True, max_length=100, null=True)),
                ('minimum', models.CharField(blank=True, max_length=100, null=True)),
                ('maximum', models.CharField(blank=True, max_length=100, null=True)),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.workout')),
            ],
        ),
    ]
